# Replace with settings for the actual production installation
spring.datasource.url=jdbc:postgresql://localhost:5432/dev?currentSchema=neurosync
spring.datasource.username=neurosync_user
spring.datasource.password=secret_pass
spring.datasource.driver-class-name=org.postgresql.Driver